--- 
development: 
  adapter: postgresql
  database: stand_db
  host: localhost
  password: test321
  username: derrick
production: 
  adapter: postgresql
  database: stand_db_prod
  host: localhost
  password: test321
  username: derrick
test: 
  adapter: postgresql
  database: stand_db_test
  host: localhost
  password: test321
  username: derrick
